### ISSUE TITLE
Don't copy music

### ISSUE THREAD

**Issue by fwsmit** [MeesCode/mmjs#9]
Als je een eigen playlist wilt maken moet je nu volgens mij muziek kopiëren naar een ander mapje. Het zou handig zijn als er een oplossing is de werkt zonder kopiëren.
Ik kan twee dingen bedenken:
- Link de bestanden ipv kopiëren (dit hoeft niet in mmjs gedaan te worden)
- Voeg ondersteuning voor afspeellijsten toe.

Wordt een van de twee al gedaan? Wat denk jij hierover?

**Comment by MeesCode** [comment]
Dit zit er al in, werkt alleen als je de applicatie in database modus draait

https://github.com/MeesCode/mmjs/blob/5496d3f8138b61b3611d252b930c4ba741192734/tui/interface.go#L172-L173
